### ISSUE TITLE
About yubikey & secrets 

### ISSUE THREAD

**Issue by reyman** [rasendubi/dotfiles#3]
Thanks a lot for you work and sharing your config.

I'm really interested to follow your way, i have mixed config (rpi4 & dell) and because i'm also a yubikey user, i have one or two questions about that. I'm already use Yubikey to remotly unlock my LUKS on RPI 4 so i'm interested to see if that will also works with secrets management.

I see you use passwordstore / pass, so you have gpg files. 
Did you decrypt these secrets with yubikey as GPG smartcard ? Do you use gpg forwarding when you're on your remote pi ? Is it working well ?  

Thanks,
Best regards,

**Comment by rasendubi** [comment]
> Did you decrypt these secrets with yubikey as GPG smartcard ?

Yes. I just had to export my GPG key to yubikey and it works.

> Do you use gpg forwarding when you're on your remote pi ? Is it working well ?

No, I don't. My rpi is mostly a backup management server and I rarely log in there.
